# Generated by Django 2.2.3 on 2021-05-06 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='mytask',
            name='created_by',
            field=models.CharField(default='Pravin', max_length=100),
        ),
    ]
