# Generated by Django 2.2.3 on 2021-05-06 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity_API', '0002_auto_20210506_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='create_date',
            field=models.DateField(default=datetime.date(2021, 5, 6), editable=False),
        ),
    ]
